Hometask 2
bcskda/smart-home-2021 pull request #2
Opened 2021-03-17 23:16 UTC by bcskda

2021-03-19 06:14 UTC, a-ivanov requested changes

2021-03-19 06:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    Map<String, Light> lightsById = new HashMap<>();
Обсуждали в 1 дз, переделайте на список.

2021-03-19 06:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public Door getDoorById(String doorId) {
Это все по 2 дз удалаем, мы не привязыаем логику к внутренней структуре.

2021-03-19 06:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void execute(Action action) {
Ещё дом.

2021-03-22 05:41 UTC, a-ivanov requested changes

2021-03-22 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void forEachRoom(Action action) {
Это деталь реализации, не надо делать этот метод публичным. Перенесите его в execute, либо сделайте private.

2021-03-22 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      SmartHomeStorage storage = new SmartHomeStorage();
В чем польза этого класса? Он просто хранит ссылку на коллекцию дверей и возвращает её. Он ни чем не отличается от коллекции. Пока у нас нет сложной логики по работе с коллекцией комнат, лучше пользоваться просто коллекцией.

2021-03-22 06:30 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      SmartHomeStorage storage = new SmartHomeStorage();
В какой-то момент так было проще сериализовать, но сейчас это уже не так, да

2021-03-23 05:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      SmartHomeStorage storage = new SmartHomeStorage();
Коллекции из коробки сериализуются в большинстве известных библиотеках.

2021-03-23 05:36 UTC, a-ivanov approved these changes

2021-03-23 05:42 UTC, merged