Hometask 3
bcskda/smart-home-2021 pull request #3
Opened 2021-03-24 21:50 UTC by bcskda

2021-03-30 05:11 UTC, a-ivanov requested changes

2021-03-30 05:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +public class Alarm implements SensorEventHandler {
Нарушение SRP, создайте отдельный обработчик для сигнализации. И отдельный класс для декоратора.

2021-03-30 05:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +        AlarmState Activate(String code);
camelCase названия методов.

2021-03-30 05:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmStateArmed.java
> +    Collection<SensorEventHandler> eventHandlers;
Удалите это, не создавайте ненужный каплинг.

2021-03-31 05:04 UTC, a-ivanov requested changes

2021-03-31 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +        return state.getClass();
Добавьте методы для работы с сигнализацией как обсуждали в группе.

2021-03-31 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/AlarmEventHandler.java
> +            actSms.execute(component);
Но только объект применяет к себе действие, а не наоборот.

2021-03-31 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/AlarmEventHandler.java
> +    void sendSms() {
В отдельный класс, SRP.

2021-03-31 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/AlarmEventHandler.java
> +    public Action onAlarmFiring() {
Эту работу должен делать отдельный класс декоратор, причём он должен менять поведение в зависимости от состояния сигнализации при обработке всех событий.

2021-04-02 04:34 UTC, a-ivanov approved these changes

2021-04-02 04:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/RunOnceDecorator.java
> +    private boolean isCalled = false;
А как возвращать его в исходное состояние, чтобы заново делал вызовы? Перезапускать приложение?

2021-04-02 06:47 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/actions/RunOnceDecorator.java
> +    private boolean isCalled = false;
Вроде isCalled - это поле инстанса

Каждый такой `new RunOnceDecorator(someRunnable)`, созданный каким-то handler-ом, будет применён к иерархии умного дома и вызовет `someRunnable` ровно один раз

При другом событии handler создаст новый Action

2021-04-02 06:50 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/actions/RunOnceDecorator.java
> +    private boolean isCalled = false;
Возможно, неправильно понял вопрос

Этот декоратор (и `PairActionDecorator`) написал, чтобы в конфигурационном коде можно было выражать "более сложную" логику пожеланий владельца дома через композицию базовых Action-ов и по возможности в конфигурационном коде, а не в многих конкретных handler-ах

2021-04-29 14:16 UTC, merged