Hometask 4
bcskda/smart-home-2021 pull request #4
Opened 2021-04-01 01:15 UTC by bcskda

2021-04-05 05:59 UTC, a-ivanov requested changes

2021-04-05 05:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +    SmartHome getSmartHome() {
Без get, это фабрики бинов.

2021-04-05 05:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +
Посмотрите гайд, обработчики - в отдельных бинах. В текущем виде очень сложно понять, что как конфигурируется.

2021-04-05 05:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +    Consumer<Action> actionConsumer;
Зачем так сложно? Смысл паттерна адаптер - адаптировать один интерфейс к другому. В вашем коде непонятно, у какому интерфейсу вы адаптируете, слишком абстрактно.

2021-04-05 10:31 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +    Consumer<Action> actionConsumer;
У "родных" EventHandler-ов метод handleEvent() возвращает Action - во втором задании сделал так, чтобы уже внешний код решал, к кому этот Action применять

EventHandler-ы в сторонней библиотеке ничего не возвращают при обработке, поэтому адаптеру нужен Consumer, чтобы передавать Action-ы на исполнение

Не уверен, что можно сделать проще, не меняя интерфейс родных EventHandler-ов

2021-04-06 15:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +    Consumer<Action> actionConsumer;
Это ничего не меняет. У вас есть какая-то логика, которая принимает Action. Перенесите её сюда. Все равно сделайте поле типом интерфейса, к которому вы адаптируете. У вас просто изменился способ получения событий.

2021-04-06 15:25 UTC, a-ivanov requested changes

2021-04-06 15:25 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +        allHandlers.add(new LogEventHandler());
См. Гайд, как перенести обработчики в разные бины.

2021-04-12 06:30 UTC, a-ivanov requested changes

2021-04-12 06:30 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +        applicationContext.getBean(CcAdaptConfiguration.class)
Разве в гайде такое было? Откуда такие идеи? Контекст в спринге используется только в инфраструкткрном коде самого фреймворка, в бизнес контексте его почти никогда не нужно использовать. Удалите, в гайде написано, как лучше сделать, чтобы не нарушать OCP в конфигурации.

2021-04-12 06:30 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
Удалите.

2021-04-12 06:30 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +        // Для данной версии либы работает
Сейчас работает, а завтра добавят название, несоападающее с вашим. Сделайте общее решение с мапой.

2021-04-16 05:50 UTC, a-ivanov requested changes

2021-04-16 05:50 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +        eventTypeMap.put("LightIsOn", EventType.LIGHT_ON);
Перенесите мапу в конфигурацию.

2021-04-16 05:50 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +    private List<EventHandler> getAllNativeHandlers(EventHandler alarmEventHandler,
Видно, что вы не читали гайд, там сказано, как сделать так, чтобы фреймворк самостоятельно собирал список бинов.

2021-04-16 06:10 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +    private List<EventHandler> getAllNativeHandlers(EventHandler alarmEventHandler,
Было удобно воспользоваться автоматическим сбором бинов здесь:
https://github.com/bcskda/smart-home-2021/pull/4/files/e42c59cfda74a3638de83182a09524f07e4fd1e2#diff-67633e254a67b454f75fdc8072a5b4f53f1a4be18cf3d52bc3c0e5d813296f49R52
Но хотелось оставить ортогональными:
- конфигурацию нашей внутренней логики (EventHandler для сенсоров) и
- адаптирование наших обработчиков к сторонней библиотеке

Поэтому казалось, что бин "список _адаптированных_ обработчиков" - не самая плохая идея. Не уверен, что понимаю, в какую сторону это нужно улучшить.

2021-04-16 06:11 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +    private List<EventHandler> getAllNativeHandlers(EventHandler alarmEventHandler,
Точнее, "список адаптированных обработчиков" сейчас как раз не бин - проблема в этом?

2021-04-16 06:25 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +    private List<EventHandler> getAllNativeHandlers(EventHandler alarmEventHandler,
Проблема в том, что вы руками создаёте и добавляете обработчики в список. При появлении новых обработчиков вам придётся не забывать их туда добавлять.
А можно просто удалить бин со списком. Там, где нужен список бинов, фреймворк их сам соберёт. 
После бина со списком обработчиков логика ок.

2021-04-28 05:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +        eventTypeMap.put("LightIsOn", EventType.LIGHT_ON);
Не исправлено.

2021-04-28 05:54 UTC, a-ivanov requested changes
Исправьте замечания

2021-04-28 07:43 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +        eventTypeMap.put("LightIsOn", EventType.LIGHT_ON);
Да, извините, пропустил это.

Сейчас мапа конфигурируется бином в `ApplicationConfiguration`. Но по-хорошему она относится только к адаптеру, и можно было бы спустить её на пакет ниже - так поступают?

2021-04-28 07:50 UTC, bcskda commented on src/main/java/ru/sbt/mipt/oop/ccadapt/EventHandlerAdaptor.java
> +        eventTypeMap.put("LightIsOn", EventType.LIGHT_ON);
В смысле, выделить отдельную конфигурацию адаптеров и спустить её в пакет ccadapt

2021-04-28 16:24 UTC, a-ivanov approved these changes

2021-04-29 14:16 UTC, merged